# https://taskfile.dev/
version: "3"

vars:
  PYTHON_BIN: python3.7
  VENVS: ./venvs/
  FLAKE8_ENV: "{{.VENVS}}flake8"
  MYPY_ENV:   "{{.VENVS}}mypy"
  FLIT_ENV:   "{{.VENVS}}flit"
  PYTEST_ENV: "{{.VENVS}}pytest"
  SPHINX_ENV: "{{.VENVS}}sphinx"
  ISORT_ENV:  "{{.VENVS}}isort"

env:
  FLIT_ROOT_INSTALL: "1"

tasks:
  venv:create:
    status:
      - "test -f {{.ENV}}/bin/activate"
    cmds:
      - "{{.PYTHON_BIN}} -m venv {{.ENV}}"
      - "{{.ENV}}/bin/python3 -m pip install -U pip setuptools wheel"
  flit:init:
    status:
      - "test -f {{.FLIT_ENV}}/bin/flit"
    deps:
      - task: venv:create
        vars:
          ENV: "{{.FLIT_ENV}}"
    cmds:
      - "{{.FLIT_ENV}}/bin/python3 -m pip install flit"
  flit:install:
    sources:
      - pyproject.toml
      - "{{.ENV}}/bin/activate"
    deps:
      - flit:init
      - task: venv:create
        vars:
          ENV: "{{.ENV}}"
    cmds:
      - >
        {{.FLIT_ENV}}/bin/flit install
        --python={{.ENV}}/bin/python3
        --deps=production
        --extras={{.EXTRA}}
  flit:build:
    deps:
      - flit:init
    cmds:
      - "{{.FLIT_ENV}}/bin/flit build"
  flit:upload:
    deps:
      - flit:build
    cmds:
      - "{{.FLIT_ENV}}/bin/flit publish"

  flake8:run:
    sources:
      - "**/*.py"
    deps:
      - task: flit:install
        vars:
          ENV: "{{.FLAKE8_ENV}}"
          EXTRA: dev
    cmds:
      - "{{.FLAKE8_ENV}}/bin/flake8 ."

  mypy:run:
    sources:
      - flake8_codes/**/*.py
    deps:
      - task: flit:install
        vars:
          ENV: "{{.MYPY_ENV}}"
          EXTRA: dev
    cmds:
      - "{{.MYPY_ENV}}/bin/mypy --ignore-missing-imports --allow-redefinition flake8_codes/"

  pytest:run:
    deps:
      - task: flit:install
        vars:
          ENV: "{{.PYTEST_ENV}}"
          EXTRA: plugins,dev
    cmds:
      - "{{.PYTEST_ENV}}/bin/pytest tests/"

  isort:run:
    sources:
      - "**/*.py"
    deps:
      - task: flit:install
        vars:
          ENV: "{{.ISORT_ENV}}"
          EXTRA: dev
    cmds:
      - "{{.ISORT_ENV}}/bin/isort ."
